name: Test
on:
  push:
    branches: master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu20.04:master
    env:
      HOMEBREW_CORE_GIT_REMOTE: ${{github.event.repository.html_url}}
      HOMEBREW_FORCE_HOMEBREW_ON_LINUX: 1
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Run brew test-bot
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot --only-formulae
