name: Test
on:
  push:
    branches: master
  pull_request:
jobs:
  test:
    name: Test MacOS
    runs-on: macos-latest
    steps:
     - name: Set up Homebrew
       uses: Homebrew/actions/setup-homebrew@master

     - name: Test Formula
       run: brew test-bot
